[program:nametag-worker]
command=/usr/bin/php /home/deploy/apps/nametag/artisan queue:work database --queue=nametag --sleep=3 --tries=3 --timeout=1200 -vvv
process_name=%(program_name)s
directory=/home/deploy/apps/nametag
user=deploy
numprocs=1
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=3600
stdout_logfile=/var/log/nametag-worker.log
stderr_logfile=/var/log/nametag-worker.err
